//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwipeSafe.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAttach
    {
        public string Id { get; set; }
        public string ReportId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Size { get; set; }
        public string Parth { get; set; }
        public string ParthThumbnail { get; set; }
        public string Type { get; set; }
    }
}
