//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwipeSafe.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessingContent
    {
        public string Id { get; set; }
        public string ProfileChildId { get; set; }
        public string Content { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public string ProcessingBy { get; set; }
    }
}
