//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwipeSafe.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileChild
    {
        public string Id { get; set; }
        public int InformationSources { get; set; }
        public Nullable<System.DateTime> ReceptionDate { get; set; }
        public string ChildName { get; set; }
        public Nullable<System.DateTime> ChildBirthdate { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string CaseLocation { get; set; }
        public string WardId { get; set; }
        public string DistrictId { get; set; }
        public string ProvinceId { get; set; }
        public string FullAddress { get; set; }
        public string CurrentHealth { get; set; }
        public string SequelGuess { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> FatherAge { get; set; }
        public string FatherJob { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> MotherAge { get; set; }
        public string MotherJob { get; set; }
        public string FamilySituation { get; set; }
        public string PeopleCare { get; set; }
        public string Support { get; set; }
        public string ProviderName { get; set; }
        public string ProviderPhone { get; set; }
        public string ProviderAddress { get; set; }
        public string ProviderNote { get; set; }
        public int ProcessingStatus { get; set; }
        public Nullable<int> SeverityLevel { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string FinishNote { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string ClosedNote { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ReportId { get; set; }
    }
}
