//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwipeSafe.Model.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportAppEntities : DbContext
    {
        public ReportAppEntities()
            : base("name=ReportAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<ChildAbuse> ChildAbuses { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<FileAttach> FileAttaches { get; set; }
        public virtual DbSet<FormsAbuse> FormsAbuses { get; set; }
        public virtual DbSet<Prisoner> Prisoners { get; set; }
        public virtual DbSet<ProcessingContent> ProcessingContents { get; set; }
        public virtual DbSet<ProfileChild> ProfileChilds { get; set; }
        public virtual DbSet<ProfileChildAbuse> ProfileChildAbuses { get; set; }
        public virtual DbSet<ProfileFileAttach> ProfileFileAttaches { get; set; }
        public virtual DbSet<ProfilePrisoner> ProfilePrisoners { get; set; }
        public virtual DbSet<ProfileReporter> ProfileReporters { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
