# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reportward' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reportward
  pod 'Moya', '~> 12.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'JGProgressHUD'
  pod 'IQKeyboardManagerSwift'
end
