//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbuseType
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public int OrderNumber { get; set; }
        public Nullable<int> ThenNumber { get; set; }
    }
}
