//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationFirst
    {
        public string Id { get; set; }
        public string ReportProfileId { get; set; }
        public Nullable<System.DateTime> PerformingDate { get; set; }
        public Nullable<int> LevelHarm { get; set; }
        public string LevelHarmNote { get; set; }
        public Nullable<int> LevelHarmContinue { get; set; }
        public string LevelHarmContinueNote { get; set; }
        public Nullable<int> TotalLevelHigh { get; set; }
        public Nullable<int> TotalLevelAverage { get; set; }
        public Nullable<int> TotalLevelLow { get; set; }
        public Nullable<int> AbilityProtectYourself { get; set; }
        public Nullable<int> AbilityReceiveSupport { get; set; }
        public string AbilityProtectYourselfNote { get; set; }
        public string AbilityReceiveSupportNote { get; set; }
        public Nullable<int> TotalAbilityHigh { get; set; }
        public Nullable<int> TotalAbilityAverage { get; set; }
        public Nullable<int> TotalAbilityLow { get; set; }
        public string Result { get; set; }
        public string UnitProvideLiving { get; set; }
        public string UnitProvideCare { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string ServiceProvideLiving { get; set; }
        public string ServiceProvideCare { get; set; }
    
        public virtual ReportProfile ReportProfile { get; set; }
    }
}
