//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InformationHubEntities : DbContext
    {
        public InformationHubEntities()
            : base("name=InformationHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbuseType> AbuseTypes { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<AreaDistrict> AreaDistricts { get; set; }
        public virtual DbSet<AreaUser> AreaUsers { get; set; }
        public virtual DbSet<AreaWard> AreaWards { get; set; }
        public virtual DbSet<CaseVerification> CaseVerifications { get; set; }
        public virtual DbSet<CodeReport> CodeReports { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<DocumentLibrary> DocumentLibraries { get; set; }
        public virtual DbSet<DocumentTye> DocumentTyes { get; set; }
        public virtual DbSet<EstimateCostAttachment> EstimateCostAttachments { get; set; }
        public virtual DbSet<EvaluationFirst> EvaluationFirsts { get; set; }
        public virtual DbSet<GroupFunction> GroupFunctions { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<Notify> Notifies { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProfileAttachment> ProfileAttachments { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<ReportForward> ReportForwards { get; set; }
        public virtual DbSet<ReportHistory> ReportHistories { get; set; }
        public virtual DbSet<ReportProfile> ReportProfiles { get; set; }
        public virtual DbSet<ReportProfileAbuseType> ReportProfileAbuseTypes { get; set; }
        public virtual DbSet<SupportAfterStatu> SupportAfterStatus { get; set; }
        public virtual DbSet<SupportPlant> SupportPlants { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
