//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileAttachment
    {
        public string Id { get; set; }
        public string ReportProfileId { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<int> Size { get; set; }
        public string Extension { get; set; }
        public string Description { get; set; }
        public string UploadBy { get; set; }
        public System.DateTime UploadDate { get; set; }
    
        public virtual ReportProfile ReportProfile { get; set; }
    }
}
