//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportProfileAbuseType
    {
        public string Id { get; set; }
        public string ReportProfileId { get; set; }
        public string AbuseTypeId { get; set; }
        public string AbuseTypeName { get; set; }
    
        public virtual ReportProfile ReportProfile { get; set; }
    }
}
