//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportProfile()
        {
            this.CaseVerifications = new HashSet<CaseVerification>();
            this.EvaluationFirsts = new HashSet<EvaluationFirst>();
            this.ProfileAttachments = new HashSet<ProfileAttachment>();
            this.ReportProfileAbuseTypes = new HashSet<ReportProfileAbuseType>();
            this.SupportAfterStatus = new HashSet<SupportAfterStatu>();
            this.SupportPlants = new HashSet<SupportPlant>();
        }
    
        public string Id { get; set; }
        public int InformationSources { get; set; }
        public string SourceNote { get; set; }
        public string ReceptionTime { get; set; }
        public Nullable<System.DateTime> ReceptionDate { get; set; }
        public string ChildName { get; set; }
        public Nullable<System.DateTime> ChildBirthdate { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string CaseLocation { get; set; }
        public string WardId { get; set; }
        public string DistrictId { get; set; }
        public string ProvinceId { get; set; }
        public string FullAddress { get; set; }
        public string CurrentHealth { get; set; }
        public string SequelGuess { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> FatherAge { get; set; }
        public string FatherJob { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> MotherAge { get; set; }
        public string MotherJob { get; set; }
        public string FamilySituation { get; set; }
        public string PeopleCare { get; set; }
        public string Support { get; set; }
        public string ProviderName { get; set; }
        public string ProviderPhone { get; set; }
        public string ProviderAddress { get; set; }
        public string ProviderNote { get; set; }
        public Nullable<int> SeverityLevel { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string FinishNote { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> StatusStep1 { get; set; }
        public Nullable<bool> StatusStep2 { get; set; }
        public Nullable<bool> StatusStep3 { get; set; }
        public Nullable<bool> StatusStep4 { get; set; }
        public Nullable<bool> StatusStep5 { get; set; }
        public Nullable<bool> StatusStep6 { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string WordTitle { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public string SummaryCase { get; set; }
        public string Alias { get; set; }
        public string TypeOther { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseVerification> CaseVerifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationFirst> EvaluationFirsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileAttachment> ProfileAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportProfileAbuseType> ReportProfileAbuseTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportAfterStatu> SupportAfterStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportPlant> SupportPlants { get; set; }
    }
}
