//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportHistory
    {
        public string Id { get; set; }
        public string ReportProfileId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Abuse { get; set; }
        public string FullAddress { get; set; }
        public int StatusProcess { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string WardId { get; set; }
        public string LocalAddress { get; set; }
        public string Code { get; set; }
    }
}
