//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportPlant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupportPlant()
        {
            this.EstimateCostAttachments = new HashSet<EstimateCostAttachment>();
        }
    
        public string Id { get; set; }
        public string ReportProfileId { get; set; }
        public Nullable<System.DateTime> PlantDate { get; set; }
        public string TitlePlant { get; set; }
        public string TargetNote { get; set; }
        public string ActionNote { get; set; }
        public string OrganizationActivities { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> IsEstimateCost { get; set; }
        public Nullable<bool> IsRemind75 { get; set; }
        public Nullable<bool> IsRemind90 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimateCostAttachment> EstimateCostAttachments { get; set; }
        public virtual ReportProfile ReportProfile { get; set; }
    }
}
