//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationHub.Model.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportAfterStatu
    {
        public string Id { get; set; }
        public string ReportProfileId { get; set; }
        public Nullable<System.DateTime> PerformingDate { get; set; }
        public string PerformingBy { get; set; }
        public Nullable<int> LevelHarm { get; set; }
        public Nullable<int> LevelApproach { get; set; }
        public Nullable<int> LevelCareObstacle { get; set; }
        public Nullable<int> TotalLevelHigh { get; set; }
        public Nullable<int> TotalLevelAverage { get; set; }
        public Nullable<int> TotalLevelLow { get; set; }
        public Nullable<int> AbilityProtectYourself { get; set; }
        public Nullable<int> AbilityKnowGuard { get; set; }
        public Nullable<int> AbilityHelpOthers { get; set; }
        public Nullable<int> TotalAbilityHigh { get; set; }
        public Nullable<int> TotalAbilityAverage { get; set; }
        public Nullable<int> TotalAbilityLow { get; set; }
        public string Result { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string SupportAfterTitle { get; set; }
        public string LevelHarmNote { get; set; }
        public string LevelApproachNote { get; set; }
        public string LevelCareObstacleNote { get; set; }
        public string AbilityProtectYourselfNote { get; set; }
        public string AbilityKnowGuardNote { get; set; }
        public string AbilityHelpOthersNote { get; set; }
    
        public virtual ReportProfile ReportProfile { get; set; }
    }
}
