//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildProfiles.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentImage
    {
        public string Id { get; set; }
        public string ShareImageId { get; set; }
        public string Name { get; set; }
        public Nullable<int> FileType { get; set; }
        public string ImagePath { get; set; }
        public string ImageThumbnailPath { get; set; }
        public Nullable<int> SizeBase { get; set; }
        public string UploadBy { get; set; }
        public System.DateTime UploadDate { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ShareImage ShareImage { get; set; }
    }
}
