//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildProfiles.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLibrary
    {
        public string Id { get; set; }
        public string DocumentTyeId { get; set; }
        public string FileName { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<int> Size { get; set; }
        public string Extension { get; set; }
        public string Description { get; set; }
        public bool IsDisplay { get; set; }
        public string UploadBy { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual DocumentTye DocumentTye { get; set; }
    }
}
