//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildProfiles.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageChildByYear
    {
        public string Id { get; set; }
        public string ChildProfileId { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumbnail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Year { get; set; }
        public string ProvinceId { get; set; }
        public string DistrictId { get; set; }
        public string WardId { get; set; }
    }
}
