//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildProfiles.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportProfile()
        {
            this.AttachFileReports = new HashSet<AttachFileReport>();
        }
    
        public string Id { get; set; }
        public string Content { get; set; }
        public string ChildProfileId { get; set; }
        public string ProcessStatus { get; set; }
        public string AreaApproverBy { get; set; }
        public Nullable<System.DateTime> AreaApproveDate { get; set; }
        public string OfficeApproveBy { get; set; }
        public Nullable<System.DateTime> OfficeApproveDate { get; set; }
        public bool IsDelete { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Description { get; set; }
        public string AreaApproverNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachFileReport> AttachFileReports { get; set; }
    }
}
