//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildProfiles.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryTemplate
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string StoryContent { get; set; }
        public string CreateBy { get; set; }
        public string UerStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsDelete { get; set; }
    }
}
