# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swipesafe' do
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
  end
  
  inhibit_all_warnings!
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swipesafe
  pod 'Moya', '~> 12.0'
  pod 'Toast-Swift', '~> 4.0.0'
  pod 'JGProgressHUD'
  pod 'Kingfisher', '~> 5.0'
  pod 'YoutubePlayer-in-WKWebView', '~> 0.2.0'
  pod 'DKImagePickerController', :subspecs => ['PhotoGallery', 'Camera', 'InlineCamera']
end
